name = "bravo"
version = "0.0.0"
target = "erlang"
internal_modules = [
  "bravo/internal",
  "bravo/internal/*",
]
description = "Comprehensive ETS bindings for Gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "Michael-Mark-Edu", repo = "bravo" }

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.5.1 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
